version: '3'
services:
  mysql:
    container_name: mysql
    hostname: mysql
    image: mysql:8.1.0
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=elib
    restart: unless-stopped
    ports:
      - "3306:3306"
  phpmyadmin:
    container_name: phpmyadmin
    hostname: phpmyadmin
    image: phpmyadmin:5.2.1
    restart: always
    links:
      - mysql
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql
      - MYSQL_USERNAME=root
      - MYSQL_ROOT_PASSWORD=admin
      - PMA_PORT=3306
      - PMA_ARBITRARY=1
    volumes:
      - /sessions
    
   
